spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${db.endpoint}/${db.name}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
  security.oauth2.resourceserver.jwt.jwk-set-uri: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json


management.endpoints.web:
  base-path: /
  exposure.include: [ "health", "info" ]

db:
  name: sentence-plan
  endpoint: localhost:5432
  username: postgres
  password: postgres

