spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${db.endpoint}/${db.name}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true


management.endpoints.web:
  base-path: /
  exposure.include: [ "health", "info" ]

db:
  name: sentence-plan
  endpoint: localhost:5432
  username: postgres
  password: postgres

---

spring.config.activate.on-profile: [ "dev", "test" ]

spring:
  security.oauth2:
    resourceserver.jwt.public-key-location: classpath:local-public-key.pub

