generic-service:
  nameOverride: hmpps-sentence-plan
  replicaCount: 2
  resources:
    requests:
      cpu: 128m
      memory: 512Mi

  image:
    repository: quay.io/hmpps/hmpps-sentence-plan
    port: 8080

  ingress:
    tlsSecretName: hmpps-sentence-plan-cert
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false

  env:
    AWS_REGION: eu-west-2
    JDK_JAVA_OPTIONS: -javaagent:/agent/agent.jar -XX:MaxRAMPercentage=75.0
    SENTRY_TRACES_SAMPLE_RATE: '0.05'
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: "org.apache.catalina.connector.ClientAbortException"

  namespace_secrets:
    hmpps-sentence-plan:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    rds-postgresql-instance-output:
      SPRING_DATASOURCE_URL: rds_instance_endpoint
      SPRING_DATASOURCE_USERNAME: database_username
      SPRING_DATASOURCE_PASSWORD: database_password
#      OAUTH2_CLIENT-ID: CLIENT_ID
#      OAUTH2_CLIENT-SECRET: CLIENT_SECRET
#      SENTRY_DSN: SENTRY_DSN

generic-prometheus-alerts:
  targetApplication: hmpps-sentence-plan

