generic-service:
  nameOverride: hmpps-sentence-plan
  replicaCount: 2
  resources:
    requests:
      cpu: 128m
      memory: 512Mi

  image:
    repository: quay.io/hmpps/hmpps-sentence-plan
    port: 8080

  ingress:
    tlsSecretName: hmpps-sentence-plan-cert
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false

  env:
    AWS_REGION: eu-west-2
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    JDK_JAVA_OPTIONS: -javaagent:/agent/agent.jar -XX:MaxRAMPercentage=75.0
    SENTRY_TRACES_SAMPLE_RATE: '0.05'
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: "org.apache.catalina.connector.ClientAbortException"

  namespace_secrets:
    hmpps-sentence-plan:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      #      OAUTH2_CLIENT-ID: CLIENT_ID
      #      OAUTH2_CLIENT-SECRET: CLIENT_SECRET
      #      SENTRY_DSN: SENTRY_DSN
    rds-postgresql-instance-output:
      DB_ENDPOINT: rds_instance_endpoint
      DB_NAME: database_name
      DB_USERNAME: database_username
      DB_PASSWORD: database_password

generic-prometheus-alerts:
  targetApplication: hmpps-sentence-plan

